In [6]:
import numpy as np #import numpy and rename as np 

In [10]:
np.array([1,2,3])

array([1, 2, 3])

### Selective import

In [13]:
from math import pi #import a specific part of a package which is pi 
from math import radians #import radians in math package

### NumPy

Provides a alternative to the regular python
    1. Calculations over entire arrays; 
    2. Easy and fast;
Code: "import numpy as np" 

In [19]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [22]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [25]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [28]:
bmi = np_weight / np_height **2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

NumPy arrays: contain only one type; Different from Python arrays 

In [32]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [36]:
python_list + python_list #Python list -- appends

[1, 2, 3, 1, 2, 3]

In [37]:
numpy_array + numpy_array #Numpy - adds 

array([2, 4, 6])

#### NumPy Subsetting

In [41]:
bmi > 23

array([False, False, False,  True, False])

In [43]:
bmi[bmi>23] #only values that are TRUE are selected

array([24.7473475])