# Introduction to Python 

In [10]:
np.array([1,2,3])

array([1, 2, 3])

### Selective import

In [13]:
from math import pi #import a specific part of a package which is pi 
from math import radians #import radians in math package

### NumPy

Provides a alternative to the regular python
    1. Calculations over entire arrays; 
    2. Easy and fast;
Code: "import numpy as np" 

In [19]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [22]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [25]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [28]:
bmi = np_weight / np_height **2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

NumPy arrays: contain only one type; Different from Python arrays 

In [32]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [36]:
python_list + python_list #Python list -- appends

[1, 2, 3, 1, 2, 3]

In [44]:
numpy_array + numpy_array #Numpy - perform addition 

array([2, 4, 6])

#### NumPy Subsetting

In [41]:
bmi > 23

array([False, False, False,  True, False])

In [46]:
bmi[bmi>23] #only values that are TRUE are selected

array([24.7473475])

Side Effect: NumPy allows you to perform vector arithmetic

#### NumPy Subsetting: Lightweight baseball players

In [6]:
#To subset both regular python lists and numpy arrays, use square brackets 
x = [4 , 9 , 6, 3, 1]
x[1]

9

In [8]:
import numpy as np
y = np.array(x)
y[1]

9

In [11]:
#For numpy, you can use boolean numpy arrays 
high = y > 5 
y[high]

array([9, 6])

#### NumPy Side Effects

In [15]:
# 1.Type coercion: numpy arrays cannot contain element of different types
# 2. typical arithmetic operators have a different meaning for regular Python 
    #lists and numpyarrays.

In [18]:
np.array([True, 1, 2]) + np.array([3, 4, False]) #True = 1, False = 0

array([4, 5, 2])

#### Subsetting NumPy Arrays

In [20]:
x = ["a", "b", "c"]
x[1]

'b'

In [22]:
np_x = np.array(x)
np_x[1]

'b'

### 2D NumPy Arrays

In [25]:
np_2d = np.array ([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6,88.4,68.7]])
np_2d #each sublist corresponds to a row, values within each list is for column

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [28]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [31]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball

np_baseball = np.array(baseball)


# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


#### Subsetting 2D NumPy Arrays

In [33]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:, 0] # : - slicing, 0 - first element 

array(['a', 'c'], dtype='<U1')

In [38]:
# baseball is available as a regular list of lists

# Import numpy package

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[2,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[:,0])

[210.   98.5]
[180. 215. 210. 188.]


#### 2D Arithmetic

In [42]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [44]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array


# Create np_baseball (3 cols)
        #np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
       #print(np_baseball + updated)

# Create numpy array: conversion
       #conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
      #print(np_baseball*conversion)

#### NumPy: Basic Statistics

In [46]:
#np.mean
#np.median
#np.corrcoef
#np.std 

##### Generate Data

In [56]:
#Arguments: distribution mean, distribution std, number of samples)
height = np.round(np.random.normal(1.75, 0.20, 5000),2) 
weight = np.round(np.random.normal(60.32, 15, 5000),2)
np_city = np.column_stack((height, weight))

In [58]:
import numpy as np
x = [1, 4, 8, 10, 12]
np.mean(x)
np.median(x)

8.0

In [62]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


In [65]:
"""

# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)
# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == "GK"]

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != "GK"]

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

"""

'\n\n# heights and positions are available as lists\n\n# Import numpy\nimport numpy as np\n\n# Convert positions and heights to numpy arrays: np_positions, np_heights\nnp_positions = np.array(positions)\nnp_heights = np.array(heights)\n# Heights of the goalkeepers: gk_heights\ngk_heights = np_heights[np_positions == "GK"]\n\n# Heights of the other players: other_heights\nother_heights = np_heights[np_positions != "GK"]\n\n# Print out the median height of goalkeepers. Replace \'None\'\nprint("Median height of goalkeepers: " + str(np.median(gk_heights)))\n\n# Print out the median height of other players. Replace \'None\'\nprint("Median height of other players: " + str(np.median(other_heights)))\n\n'